// lang: UI string table. Entries are in str_id_t order; keep them in sync.
#include "lang.h"
#include <string.h>

typedef struct {
    const char *code;   // ISO 639-1
    const char *name;   // shown in the selector, in its own language
    const char *s[STR__COUNT];
} lang_def_t;

// To add a language later: append another lang_def_t with its translations in the
// same order as str_id_t. Nothing else changes.
static const lang_def_t LANGS[] = {
    {
        .code = "en", .name = "English",
        .s = {
            [STR_NOW_PLAYING]        = "Now playing",
            [STR_WEBRADIOS]          = "Web radios",
            [STR_PODCASTS]           = "Podcasts",
            [STR_LIBRARY]            = "Library",
            [STR_ARTISTS]            = "Artists",
            [STR_ALBUMS]             = "Albums",
            [STR_EPISODES]           = "Episodes",
            [STR_SDCARD]             = "SD card",
            [STR_SETTINGS]           = "Settings",
            [STR_CONFIG_PAGE]        = "Config page",
            [STR_SETUP_WIFI]         = "Setup Wi-Fi",
            [STR_MUSIC_LIBRARY]      = "Music library",
            [STR_BY_ARTIST]          = "By artist",
            [STR_BY_ALBUM]           = "By album",
            [STR_CONFIG_PAGE_QR]     = "Config page (QR)",
            [STR_SETUP_HOTSPOT_QR]   = "Setup hotspot (QR)",
            [STR_SYNC_LIBRARY]       = "Sync library",
            [STR_REFRESH_PODCASTS]   = "Refresh podcasts",
            [STR_NO_SD]              = "No SD card",
            [STR_NO_EPISODES]        = "No episodes yet.",
            [STR_EMPTY_LIBRARY]      = "Empty library. Scan it from Settings or the web page.",
            [STR_REFRESHING_FEED]    = "Refreshing feed...",
            [STR_REFRESHING_ALL]     = "Refreshing all feeds...",
            [STR_REFRESHING]         = "Refreshing...",
            [STR_SCAN_JOIN_WIFI]     = "Scan to join Wi-Fi",
            [STR_CONFIG_AFTER_JOIN]  = "Config opens after joining",
            [STR_SCAN_CONFIG_PAGE]   = "Scan to open the config page",
            [STR_SCAN_HOTSPOT]       = "Scan to join the setup hotspot",
            [STR_ACTIVE_DURING_SETUP]= "(active only during setup)",
            [STR_SCANNING_SD]        = "Scanning the SD card...",
            [STR_SYNC_NOW]           = "Synchronize now",
            [STR_REFRESH_ALL_FEEDS]  = "Refresh all feeds",
            [STR_STOP_PLAYBACK_FIRST]= "Stop playback first",
            [STR_REFRESH_DONE_FMT]   = "Done. %u podcast feed(s).",
            [STR_SETUP_HEADER_FMT]   = "Bugne %s setup",
            [STR_LANGUAGE]           = "Language",
            [STR_NO_WEBRADIOS]       = "No web radios yet. Add them on the config web page.",
            [STR_NO_PODCASTS]        = "No podcasts yet. Add RSS feeds on the config web page.",
            [STR_EMPTY_FOLDER]       = "Empty folder.",
            [STR_TRACKS_INDEXED_FMT] = "%u tracks indexed.",
            [STR_PODCAST_FEEDS_FMT]  = "%u podcast feed(s).",
            [STR_CONNECTING]         = "connecting...",
            [STR_RECONNECTING]       = "Reconnecting...",
            [STR_STREAM_FAILED]      = "Stream unavailable. Check the connection.",
            [STR_PLAYBACK_FAILED]    = "Cannot play this file.",
            [STR_REFRESH_FAILED]     = "Refresh failed. Check the connection.",
            [STR_END_OF_LIST]        = "End of the list.",
            [STR_WAITING_WIFI]       = "Not downloaded. Waiting for Wi-Fi.",
            [STR_GAME]               = "Times tables",
            [STR_SCORE_FMT]          = "Score: %u",
            [STR_BEST_FMT]           = "Best: %u",
            [STR_CORRECT_FMT]        = "Correct! +%d",
            [STR_TRY_AGAIN]          = "Try again!",
            [STR_NEW_BEST]           = "New high score!",
            [STR_GAME_PICK_TABLES]   = "Choose your tables",
            [STR_GAME_ALL]           = "All",
            [STR_GAME_NONE]          = "None",
            [STR_GAME_PICK_ONE]      = "Pick at least one table",
            [STR_THEME]              = "Theme",
            [STR_THEME_LIGHT]        = "Light",
            [STR_THEME_DARK]         = "Dark",
            [STR_THEME_BLUE]         = "Blue",
            [STR_THEME_OCEAN]        = "Ocean",
            [STR_THEME_PINK]         = "Pink",
            [STR_THEME_FOREST]       = "Forest",
            [STR_THEME_ORANGE]       = "Orange",
            [STR_ALARM]              = "Alarm clock",
            [STR_ALARM_ENABLED]      = "Alarm on",
            [STR_ALARM_VOLUME]       = "Alarm volume",
            [STR_ALARM_SOURCE]       = "Alarm sound",
            [STR_ALARM_SD_UNSET]     = "SD track: choose on the web page",
            [STR_ALARM_BEEP]         = "Alarm tone",
            [STR_ALARM_N_FMT]        = "Alarm %d",
            [STR_ALARM_OFF]          = "Off",
            [STR_QUIET_HOURS]        = "Quiet time: playback is off.",
            [STR_LIMIT_REACHED]      = "Listening time is up for today.",
            [STR_LIMIT_5MIN]         = "5 minutes left for today",
            [STR_DAY_LETTERS]        = "MTWTFSS",
            [STR_SNOOZE_UNTIL_FMT]   = "Alarm at %02d:%02d",
            [STR_TIME_NOT_SET]       = "Clock not set yet (needs Wi-Fi)",
            [STR_SLEEP_OFF]          = "Sleep timer off",
            [STR_SLEEP_SET_FMT]      = "Sleep timer: %d min",
            [STR_SLEEP_SET_EOT]      = "Sleep timer: end of track",
            [STR_SLEEP_REMAIN_FMT]   = "%d min",  // compact: shown in a narrow top corner label
            [STR_SLEEP_REMAIN_EOT]   = "End",
            [STR_SLEEP_STOPPED]      = "Sleep timer: stopped",
            [STR_FAVORITES]          = "Favorites",
            [STR_NO_FAVORITES]       = "No favorites yet. Tap + while something plays.",
            [STR_FAV_ADDED]          = "Added to favorites",
            [STR_FAV_REMOVED]        = "Removed from favorites",
            [STR_FAV_LIST_FULL]      = "Favorites list is full",
            [STR_FAV_MISSING]        = "No longer available",
            [STR_FAV_OFFLINE]        = "Wi-Fi needed for web radios",
            [STR_STREAK_FMT]         = "Streak: %d",
            [STR_MAX_STREAK_FMT]     = "Max streak: %d",
            [STR_RESET_MSG]          = "Score reset!",
            [STR_TUNER]              = "Tuner",
            [STR_TUNER_PLAY_NOTE]    = "Play a note",
            [STR_MEMOS]              = "Memos",
            [STR_MEMO_RECORD]        = "New memo",
            [STR_MEMO_KEEP]          = "Keep",
            [STR_MEMO_SEND]          = "Send",
            [STR_MEMO_DISCARD]       = "Discard",
            [STR_MEMO_TAP_RECORD]    = "Tap to record",
            [STR_MEMO_SEARCHING]     = "Looking for other Bugnes...",
            [STR_MEMO_NO_PEERS]      = "No other Bugne found",
            [STR_MEMO_SEND_ALL]      = "Send to all",
            [STR_MEMO_SENDING]       = "Sending...",
            [STR_MEMO_SENT]          = "Sent!",
            [STR_MEMO_SEND_FAILED]   = "Send failed",
            [STR_MEMO_NEW_FROM_FMT]  = "New memo from %s",
            [STR_MEMO_FROM_FMT]      = "From %s",
            [STR_MEMO_MINE_FMT]      = "Memo %d",
            [STR_MEMO_FULL]          = "Memo box is full",
            [STR_MEMO_EMPTY]         = "No memos yet",
            [STR_MEMO_REC_FAILED]    = "Recording failed",
            [STR_TALKIE]             = "Walkie-talkie",
            [STR_TALKIE_HOLD]        = "Hold to talk",
            [STR_TALKIE_HOLD_HINT]   = "Hold the button to talk",
            [STR_TALKIE_LEFT_MEMO]   = "Left as a memo",
        },
    },
    {
        .code = "fr", .name = "Français",
        .s = {
            [STR_NOW_PLAYING]        = "Lecture en cours",
            [STR_WEBRADIOS]          = "Radios web",
            [STR_PODCASTS]           = "Podcasts",
            [STR_LIBRARY]            = "Bibliothèque",
            [STR_ARTISTS]            = "Artistes",
            [STR_ALBUMS]             = "Albums",
            [STR_EPISODES]           = "Épisodes",
            [STR_SDCARD]             = "Carte SD",
            [STR_SETTINGS]           = "Réglages",
            [STR_CONFIG_PAGE]        = "Page de config",
            [STR_SETUP_WIFI]         = "Config Wi-Fi",
            [STR_MUSIC_LIBRARY]      = "Bibliothèque musicale",
            [STR_BY_ARTIST]          = "Par artiste",
            [STR_BY_ALBUM]           = "Par album",
            [STR_CONFIG_PAGE_QR]     = "Page de config (QR)",
            [STR_SETUP_HOTSPOT_QR]   = "Hotspot de config (QR)",
            [STR_SYNC_LIBRARY]       = "Synchroniser",
            [STR_REFRESH_PODCASTS]   = "Rafraîchir les podcasts",
            [STR_NO_SD]              = "Pas de carte SD",
            [STR_NO_EPISODES]        = "Aucun épisode.",
            [STR_EMPTY_LIBRARY]      = "Bibliothèque vide. Lancez un scan depuis les Réglages ou la page web.",
            [STR_REFRESHING_FEED]    = "Rafraîchissement du flux...",
            [STR_REFRESHING_ALL]     = "Rafraîchissement de tous les flux...",
            [STR_REFRESHING]         = "Rafraîchissement...",
            [STR_SCAN_JOIN_WIFI]     = "Scannez pour rejoindre le Wi-Fi",
            [STR_CONFIG_AFTER_JOIN]  = "La config s'ouvre après connexion",
            [STR_SCAN_CONFIG_PAGE]   = "Scannez pour ouvrir la page de config",
            [STR_SCAN_HOTSPOT]       = "Scannez pour rejoindre le hotspot",
            [STR_ACTIVE_DURING_SETUP]= "(actif seulement en configuration)",
            [STR_SCANNING_SD]        = "Scan de la carte SD...",
            [STR_SYNC_NOW]           = "Synchroniser maintenant",
            [STR_REFRESH_ALL_FEEDS]  = "Rafraîchir tous les flux",
            [STR_STOP_PLAYBACK_FIRST]= "Arrêtez d'abord la lecture",
            [STR_REFRESH_DONE_FMT]   = "Terminé. %u flux de podcast.",
            [STR_SETUP_HEADER_FMT]   = "Bugne %s : config",
            [STR_LANGUAGE]           = "Langue",
            [STR_NO_WEBRADIOS]       = "Aucune radio web. Ajoutez-les sur la page de config.",
            [STR_NO_PODCASTS]        = "Aucun podcast. Ajoutez des flux RSS sur la page de config.",
            [STR_EMPTY_FOLDER]       = "Dossier vide.",
            [STR_TRACKS_INDEXED_FMT] = "%u pistes indexées.",
            [STR_PODCAST_FEEDS_FMT]  = "%u flux de podcast.",
            [STR_CONNECTING]         = "connexion...",
            [STR_RECONNECTING]       = "Reconnexion...",
            [STR_STREAM_FAILED]      = "Flux indisponible. Vérifiez la connexion.",
            [STR_PLAYBACK_FAILED]    = "Impossible de lire ce fichier.",
            [STR_REFRESH_FAILED]     = "Échec du rafraîchissement. Vérifiez la connexion.",
            [STR_END_OF_LIST]        = "Fin de la liste.",
            [STR_WAITING_WIFI]       = "Non téléchargé. En attente du Wi-Fi.",
            [STR_GAME]               = "Multiplications",
            [STR_SCORE_FMT]          = "Score : %u",
            [STR_BEST_FMT]           = "Record : %u",
            [STR_CORRECT_FMT]        = "Bravo ! +%d",
            [STR_TRY_AGAIN]          = "Encore un essai !",
            [STR_NEW_BEST]           = "Nouveau record !",
            [STR_GAME_PICK_TABLES]   = "Choisis tes tables",
            [STR_GAME_ALL]           = "Tout",
            [STR_GAME_NONE]          = "Aucune",
            [STR_GAME_PICK_ONE]      = "Choisis au moins une table",
            [STR_THEME]              = "Thème",
            [STR_THEME_LIGHT]        = "Clair",
            [STR_THEME_DARK]         = "Sombre",
            [STR_THEME_BLUE]         = "Bleu",
            [STR_THEME_OCEAN]        = "Océan",
            [STR_THEME_PINK]         = "Rose",
            [STR_THEME_FOREST]       = "Forêt",
            [STR_THEME_ORANGE]       = "Orange",
            [STR_ALARM]              = "Réveil",
            [STR_ALARM_ENABLED]      = "Réveil activé",
            [STR_ALARM_VOLUME]       = "Volume du réveil",
            [STR_ALARM_SOURCE]       = "Sonnerie",
            [STR_ALARM_SD_UNSET]     = "Piste SD : à choisir sur la page web",
            [STR_ALARM_BEEP]         = "Sonnerie intégrée",
            [STR_ALARM_N_FMT]        = "Réveil %d",
            [STR_ALARM_OFF]          = "Désactivé",
            [STR_QUIET_HOURS]        = "Temps calme : lecture désactivée.",
            [STR_LIMIT_REACHED]      = "Temps d'écoute épuisé pour aujourd'hui.",
            [STR_LIMIT_5MIN]         = "Plus que 5 minutes aujourd'hui",
            [STR_DAY_LETTERS]        = "LMMJVSD",
            [STR_SNOOZE_UNTIL_FMT]   = "Rappel à %02dh%02d",
            [STR_TIME_NOT_SET]       = "Horloge pas encore réglée (Wi-Fi requis)",
            [STR_SLEEP_OFF]          = "Minuterie désactivée",
            [STR_SLEEP_SET_FMT]      = "Minuterie : %d min",
            [STR_SLEEP_SET_EOT]      = "Minuterie : fin de piste",
            [STR_SLEEP_REMAIN_FMT]   = "%d min",
            [STR_SLEEP_REMAIN_EOT]   = "Fin",
            [STR_SLEEP_STOPPED]      = "Minuterie : arrêt",
            [STR_FAVORITES]          = "Favoris",
            [STR_NO_FAVORITES]       = "Aucun favori. Touchez + pendant une lecture.",
            [STR_FAV_ADDED]          = "Ajouté aux favoris",
            [STR_FAV_REMOVED]        = "Retiré des favoris",
            [STR_FAV_LIST_FULL]      = "Liste des favoris pleine",
            [STR_FAV_MISSING]        = "N'est plus disponible",
            [STR_FAV_OFFLINE]        = "Wi-Fi requis pour les radios",
            [STR_STREAK_FMT]         = "Série : %d",
            [STR_MAX_STREAK_FMT]     = "Série max : %d",
            [STR_RESET_MSG]          = "Score à zéro !",
            [STR_TUNER]              = "Accordeur",
            [STR_TUNER_PLAY_NOTE]    = "Jouez une note",
            [STR_MEMOS]              = "Mémos",
            [STR_MEMO_RECORD]        = "Nouveau",  // "Nouveau mémo" overflows the portrait title box
            [STR_MEMO_KEEP]          = "Garder",
            [STR_MEMO_SEND]          = "Envoyer",
            [STR_MEMO_DISCARD]       = "Jeter",
            [STR_MEMO_TAP_RECORD]    = "Touchez pour enregistrer",
            [STR_MEMO_SEARCHING]     = "Recherche d'autres Bugnes...",
            [STR_MEMO_NO_PEERS]      = "Aucune autre Bugne trouvée",
            [STR_MEMO_SEND_ALL]      = "À toutes",
            [STR_MEMO_SENDING]       = "Envoi...",
            [STR_MEMO_SENT]          = "Envoyé !",
            [STR_MEMO_SEND_FAILED]   = "Échec de l'envoi",
            [STR_MEMO_NEW_FROM_FMT]  = "Nouveau mémo de %s",
            [STR_MEMO_FROM_FMT]      = "De %s",
            [STR_MEMO_MINE_FMT]      = "Mémo %d",
            [STR_MEMO_FULL]          = "Boîte à mémos pleine",
            [STR_MEMO_EMPTY]         = "Pas encore de mémo",
            [STR_MEMO_REC_FAILED]    = "Échec de l'enregistrement",
            [STR_TALKIE]             = "Talkie-walkie",
            [STR_TALKIE_HOLD]        = "Maintenir pour parler",
            [STR_TALKIE_HOLD_HINT]   = "Maintenez le bouton pour parler",
            [STR_TALKIE_LEFT_MEMO]   = "Laissé en mémo",
        },
    },
};

#define LANG_N (sizeof(LANGS) / sizeof(LANGS[0]))

static int s_lang;  // index into LANGS; default English

const char *T(str_id_t id)
{
    if (id < 0 || id >= STR__COUNT) return "";
    const char *v = LANGS[s_lang].s[id];
    if (!v) v = LANGS[0].s[id];   // fall back to English if a translation is missing
    return v ? v : "";
}

void lang_set_code(const char *code)
{
    if (!code) return;
    for (size_t i = 0; i < LANG_N; i++) {
        if (strcmp(LANGS[i].code, code) == 0) { s_lang = (int)i; return; }
    }
    s_lang = 0;  // unknown -> English
}

const char *lang_code(void) { return LANGS[s_lang].code; }
size_t lang_count(void) { return LANG_N; }
const char *lang_code_at(size_t i) { return i < LANG_N ? LANGS[i].code : ""; }
const char *lang_name_at(size_t i) { return i < LANG_N ? LANGS[i].name : ""; }
